name: Bug
description: 버그 수정 작업
title: "[Fix] "
labels: ["fix", "bug"]
body:
  - type: textarea
    id: details
    attributes:
      label: 내용
      description: 버그를 간단히 설명하고, 필요한 내용을 아래 구역에 작성해주세요.
      value: |
        ## 간단 설명

        -

        ---

        ## 재현 방법

        -

        ---

        ## 기대 결과

        -

        ---

        ## 실제 결과

        -
    validations:
      required: true