name: Chore
description: 설정, 문서, 패키지, 레포 관리 작업
title: "[Chore] "
labels: ["chore"]
body:
  - type: textarea
    id: details
    attributes:
      label: 내용
      description: 작업을 간단히 설명하고, 필요한 내용을 아래 구역에 작성해주세요.
      value: |
        ## 간단 설명

        -

        ---

        ## 작업 내용

        -

        ---

        ## 완료 조건

        - [ ]
    validations:
      required: true